[providers]
# Anthropic provider configuration
[providers.anthropic]
base_url = "https://as.ctok.ai/api"
api_key = "sk-ant-your-api-key-here"


[server]
host = "127.0.0.1"
port = 8080

[database]
url="./sessions.db"

[logging]
level = "info"
format = "text"  # "json" or "text"